server:
  port: 7070

spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/