server:
  port: 8081

spring:
  application:
    name: discount
  datasource:
    url: jdbc:mysql://localhost/anisa-microservice
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/